/**
 * ぐんまこどもイベント — イベントデータ
 * =========================================
 * イベントを追加・編集・削除するにはこのファイルだけ変更すればOKです。
 *
 * 【追加の手順】
 *   1. 既存の { ... }, の後ろに新しい { ... }, を追加する
 *   2. id は他と重複しない数字にする（最後の id +1 が簡単）
 *   3. ファイルを保存してブラウザをリロード
 *
 * 【各フィールドの説明】
 *   id          : 重複しない番号（例: 21）
 *   title       : イベント名
 *   emoji       : アイコン絵文字（🎨 🦕 🌿 など）
 *   category    : "experience" / "exhibition" / "nature" / "culture" / "festival"
 *   categoryLabel: カテゴリ表示名（「体験・工作」「展覧会」「自然・アウトドア」「文化・学習」「祭り・フェスタ」）
 *   area        : 市町村名（例: "前橋市"）
 *   venue       : 会場名
 *   startDate   : 開始日 "YYYY-MM-DD"
 *   endDate     : 終了日 "YYYY-MM-DD"（1日だけの場合は startDate と同じ）
 *   tags        : タグ配列（例: ["工作", "無料", "夏休み"]）
 *   desc        : 説明文（1〜3文程度）
 *   url         : 詳細ページURL
 *   free        : 無料なら true、有料なら false
 *   age         : 対象年齢（例: "全年齢" / "小学生〜" / "3歳〜"）
 */

// ↓ この配列にイベントを追加・編集してください ↓
const EVENTS = [
  {
    id: 1,
    title: "群馬県立自然史博物館 特別展「大恐竜展 ～ゴビ砂漠の秘密～」",
    emoji: "🦕",
    category: "exhibition",
    categoryLabel: "展覧会",
    area: "富岡市",
    venue: "群馬県立自然史博物館",
    startDate: "2026-04-25",
    endDate: "2026-07-20",
    tags: ["恐竜", "化石", "自然科学", "博物館"],
    desc: "モンゴルのゴビ砂漠で発見された恐竜化石を中心に、迫力満点の標本を展示。子ども向け体験コーナーも充実！",
    url: "https://www.gmnh.pref.gunma.jp/",
    free: false,
    age: "全年齢",
  },
  {
    id: 2,
    title: "高崎市少年科学館 夏休みロケット工作教室",
    emoji: "🚀",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "高崎市",
    venue: "高崎市少年科学館",
    startDate: "2026-07-19",
    endDate: "2026-07-27",
    tags: ["工作", "ロケット", "科学", "夏休み"],
    desc: "水ロケットを手作りして飛ばしてみよう！科学の原理をわかりやすく解説しながら楽しく工作します。",
    url: "https://www.city.takasaki.gunma.jp/",
    free: false,
    age: "小学生〜",
  },
  {
    id: 3,
    title: "前橋こどもフェスタ2026",
    emoji: "🎪",
    category: "festival",
    categoryLabel: "祭り・フェスタ",
    area: "前橋市",
    venue: "前橋市中央児童遊園（るなぱあく）",
    startDate: "2026-05-24",
    endDate: "2026-05-25",
    tags: ["フェスタ", "体験", "無料", "遊び"],
    desc: "前橋市最大の子どもイベント！ステージショー、縁日、工作体験、飲食ブースが大集合。入場無料。",
    url: "https://www.city.maebashi.gunma.jp/",
    free: true,
    age: "全年齢",
  },
  {
    id: 4,
    title: "群馬サファリパーク 春のふれあいフェスティバル",
    emoji: "🦁",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "富岡市",
    venue: "群馬サファリパーク",
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    tags: ["動物", "ふれあい", "サファリ", "自然"],
    desc: "ゾウやキリンなど大型動物に直接エサをあげよう！春限定の赤ちゃん動物ふれあいコーナーも開設。",
    url: "https://www.safari.co.jp/",
    free: false,
    age: "全年齢",
  },
  {
    id: 5,
    title: "桐生市市民文化会館 子ども劇場「ピノキオの冒険」",
    emoji: "🎭",
    category: "culture",
    categoryLabel: "文化・学習",
    area: "桐生市",
    venue: "桐生市市民文化会館",
    startDate: "2026-05-20",
    endDate: "2026-05-20",
    tags: ["演劇", "舞台", "ピノキオ", "観劇"],
    desc: "本格舞台劇「ピノキオの冒険」。プロの俳優たちによる迫力の舞台を親子でお楽しみください。",
    url: "https://www.city.kiryu.lg.jp/",
    free: false,
    age: "3歳〜",
  },
  {
    id: 6,
    title: "太田市美術館・図書館 こどもアートワークショップ",
    emoji: "🎨",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "太田市",
    venue: "太田市美術館・図書館",
    startDate: "2026-05-18",
    endDate: "2026-05-18",
    tags: ["アート", "ワークショップ", "絵画", "工作"],
    desc: "アーティストと一緒にオリジナル作品を制作！今月のテーマは「色の魔法」。画材は全て用意します。",
    url: "https://www.artmuseumlibraryota.jp/",
    free: false,
    age: "4歳〜小学生",
  },
  {
    id: 7,
    title: "ぐんまこどもの国 自然体験ウォーク",
    emoji: "🌿",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "太田市",
    venue: "ぐんまこどもの国",
    startDate: "2026-04-29",
    endDate: "2026-05-31",
    tags: ["自然", "ウォーク", "体験", "野外"],
    desc: "広大な自然の中でネイチャーウォーク。植物・昆虫・野鳥の観察をガイドと一緒に楽しもう！",
    url: "https://www.gunkoku.jp/",
    free: false,
    age: "全年齢",
  },
  {
    id: 8,
    title: "群馬県立歴史博物館 親子体験教室「古代土器を作ろう」",
    emoji: "🏺",
    category: "culture",
    categoryLabel: "文化・学習",
    area: "高崎市",
    venue: "群馬県立歴史博物館",
    startDate: "2026-05-17",
    endDate: "2026-05-17",
    tags: ["歴史", "土器", "体験", "縄文"],
    desc: "縄文・弥生時代の土器作りを体験。本物の技法で粘土を成形し、模様をつけて作品を完成させます。",
    url: "https://grekisi.pref.gunma.jp/",
    free: false,
    age: "小学生〜",
  },
  {
    id: 9,
    title: "榛名湖自然観察会 〜高山植物と野鳥を探そう〜",
    emoji: "🐦",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "高崎市",
    venue: "榛名湖畔",
    startDate: "2026-06-07",
    endDate: "2026-06-07",
    tags: ["自然観察", "野鳥", "植物", "榛名湖"],
    desc: "榛名湖周辺の豊かな自然を専門ガイドと探索。双眼鏡を使った野鳥観察と高山植物の識別を学びます。",
    url: "https://www.haruna.gr.jp/",
    free: false,
    age: "5歳〜",
  },
  {
    id: 10,
    title: "藤岡市みかぼみらい館 プラネタリウム特別投映「宇宙旅行へ行こう！」",
    emoji: "🌟",
    category: "culture",
    categoryLabel: "文化・学習",
    area: "藤岡市",
    venue: "藤岡市みかぼみらい館",
    startDate: "2026-05-03",
    endDate: "2026-05-31",
    tags: ["プラネタリウム", "宇宙", "星", "科学"],
    desc: "最新のデジタルプラネタリウムで全天周映像を体感！子ども向けの解説付きで星座や惑星の旅を楽しもう。",
    url: "https://www.mikaboq.com/",
    free: false,
    age: "3歳〜",
  },
  {
    id: 11,
    title: "みなかみ町 川遊び＆野外キャンプ体験",
    emoji: "🏕️",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "みなかみ町",
    venue: "利根川河川敷（みなかみ）",
    startDate: "2026-07-25",
    endDate: "2026-07-26",
    tags: ["キャンプ", "川遊び", "アウトドア", "1泊"],
    desc: "清流・利根川で川遊び＆テント泊体験！飯盒炊飯やキャンプファイヤーも。自然の中で感性を育てます。",
    url: "https://www.town.minakami.gunma.jp/",
    free: false,
    age: "小学生〜",
  },
  {
    id: 12,
    title: "群馬県立近代美術館 こどもアートワークショップ「版画を作ろう」",
    emoji: "🖼️",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "高崎市",
    venue: "群馬県立近代美術館",
    startDate: "2026-05-11",
    endDate: "2026-06-08",
    tags: ["版画", "アート", "美術館", "ワークショップ"],
    desc: "木版画の技法を学び、世界に1枚だけのオリジナル版画を制作。毎週日曜日開催、要事前申込。",
    url: "https://mmag.pref.gunma.jp/",
    free: false,
    age: "小学生〜",
  },
  {
    id: 13,
    title: "前橋市児童文化センター 工作まつり2026",
    emoji: "🔧",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "前橋市",
    venue: "前橋市児童文化センター",
    startDate: "2026-05-18",
    endDate: "2026-05-18",
    tags: ["工作", "まつり", "無料", "ものづくり"],
    desc: "紙工作・木工・電子工作など20種類以上の工作体験ブースが集結！参加無料で気軽に立ち寄れます。",
    url: "https://www.city.maebashi.gunma.jp/",
    free: true,
    age: "全年齢",
  },
  {
    id: 14,
    title: "群馬県昆虫の森 昆虫観察ツアー「初夏の虫さがし」",
    emoji: "🦋",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "桐生市",
    venue: "群馬県昆虫の森",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    tags: ["昆虫", "観察", "自然", "捕虫"],
    desc: "専門スタッフと一緒にチョウやバッタなどを採集・観察！捕まえた虫の名前や生態を詳しく教えます。",
    url: "https://www.gmnh.pref.gunma.jp/insect/",
    free: false,
    age: "全年齢",
  },
  {
    id: 15,
    title: "碓氷峠の森公園 こどもまつり in 安中",
    emoji: "🎠",
    category: "festival",
    categoryLabel: "祭り・フェスタ",
    area: "安中市",
    venue: "碓氷峠の森公園",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
    tags: ["まつり", "無料", "遊具", "フリマ"],
    desc: "碓氷峠の自然の中で開催する子どもまつり！乗り物体験・フリーマーケット・ステージイベントが楽しめます。",
    url: "https://www.city.annaka.lg.jp/",
    free: true,
    age: "全年齢",
  },
  {
    id: 16,
    title: "高崎市染料植物園 草木染め体験教室",
    emoji: "🌺",
    category: "experience",
    categoryLabel: "体験・工作",
    area: "高崎市",
    venue: "高崎市染料植物園",
    startDate: "2026-05-24",
    endDate: "2026-05-24",
    tags: ["草木染め", "体験", "植物", "ものづくり"],
    desc: "園内に咲く草木を使って布を染める体験！植物の色の不思議を楽しみながら、世界に一つのハンカチを作ります。",
    url: "https://www.city.takasaki.gunma.jp/",
    free: false,
    age: "小学生〜大人",
  },
  {
    id: 17,
    title: "伊勢崎市こどもの日スペシャルイベント",
    emoji: "🎏",
    category: "festival",
    categoryLabel: "祭り・フェスタ",
    area: "伊勢崎市",
    venue: "伊勢崎市文化会館",
    startDate: "2026-05-03",
    endDate: "2026-05-05",
    tags: ["こどもの日", "無料", "ゲーム", "体験"],
    desc: "こどもの日を記念した3日間のお祭り！スタンプラリー・縁日ゲーム・工作ブースが無料で楽しめます。",
    url: "https://www.city.isesaki.lg.jp/",
    free: true,
    age: "全年齢",
  },
  {
    id: 18,
    title: "渋川市 伊香保こども冒険キャンプ",
    emoji: "⛺",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "渋川市",
    venue: "伊香保グリーン牧場",
    startDate: "2026-08-08",
    endDate: "2026-08-10",
    tags: ["キャンプ", "冒険", "2泊3日", "牧場"],
    desc: "伊香保の自然の中での2泊3日冒険キャンプ。牧場体験・ハイキング・星空観察・飯盒炊飯など盛りだくさん！",
    url: "https://www.greenbokujo.co.jp/",
    free: false,
    age: "小学3年〜中学生",
  },
  {
    id: 19,
    title: "桐生市おりひめ子ども機織り体験",
    emoji: "🧵",
    category: "culture",
    categoryLabel: "文化・学習",
    area: "桐生市",
    venue: "桐生市産業文化センター",
    startDate: "2026-06-14",
    endDate: "2026-06-14",
    tags: ["機織り", "伝統文化", "体験", "絹"],
    desc: "絹の街・桐生の伝統工芸、機織りを体験！古い機械で布を織る体験は大人も子どもも夢中になります。",
    url: "https://www.city.kiryu.lg.jp/",
    free: false,
    age: "小学生〜",
  },
  {
    id: 20,
    title: "前橋市 敷島公園バラまつり子どもワークショップ",
    emoji: "🌹",
    category: "nature",
    categoryLabel: "自然・アウトドア",
    area: "前橋市",
    venue: "敷島公園ばら園",
    startDate: "2026-05-16",
    endDate: "2026-05-25",
    tags: ["バラ", "公園", "無料", "写真"],
    desc: "日本有数のバラ園で開催するバラまつり期間中のこどもワークショップ。バラの押し花づくりや写真教室など。",
    url: "https://www.city.maebashi.gunma.jp/",
    free: true,
    age: "全年齢",
  },
  // ↑ 新しいイベントは↑のカンマの後ろに追加してください ↑
  // 例:
  // {
  //   id: 21,
  //   title: "○○市 △△体験教室",
  //   emoji: "🎯",
  //   category: "experience",
  //   categoryLabel: "体験・工作",
  //   area: "○○市",
  //   venue: "△△センター",
  //   startDate: "2026-06-01",
  //   endDate: "2026-06-01",
  //   tags: ["体験", "工作"],
  //   desc: "イベントの説明文。",
  //   url: "https://example.com/",
  //   free: false,
  //   age: "小学生〜",
  // },
];
